### PR TITLE
Dotnet core support

### PR DESCRIPTION
**Pull request by jornj**
This version should support both .NET 4.5.1 and NetStandard 2.0. 
The csproj files are 'minimized' and I've removed obsolete files, such as packages.config and .nuspec files.

It is possible you want to clean up the web-project, that was just based on a template, and I might have messed up the attribute support there.

I've tested with 'dotnet restore', 'dotnet build', 'dotnet test' and 'dotnet package'.

### CODE REVIEW

**Comment by dradovic** [comment]
Any plans to merge this soon (or to support .NET Core/Standard)?

**Comment by jornj** [comment]
@janv8000 should review the pull request and especially see if the web-project is usable. I'm currently not using the code myself, but it would be great if it had value for others.

**Comment by janv8000** [comment]
Hi Jørn, thx for the PR!

* You can ignore the .Web project (~= delete from solution), I apparently never got around to adding IBAN.isValid to source control and now I can't find it anywhere :)
* Please retarget to the lowest possible .NET Standard version, I believe BigInteger requires 1.1

**Comment by janv8000** [comment]
Thank you for your changes, I've merged them into master.

https://www.nuget.org/packages/IbanValidation/2.0.0 is/was allready targetting .netstandard1.1 so should be consumable by .netcore2+ .

Upcoming https://www.nuget.org/packages/IbanValidation/2.1.0 will be .NET Standard 2.0 only because of https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#which-net-standard-version-to-target

**Comment by janv8000** [comment]
Merged into master

**Pull request closed without merging**
